[tool.black]
extend-exclude = '(.*\/migrations/*|\.env)'
icons = true
line-length = 80

[tool.isort]
skip_glob = ['*/migrations/**']
extend_skip_glob = [".env/*"]
lines_after_imports = 2
force_single_line = true
use_parentheses = true
include_trailing_comma = true
multi_line_output = 3
src_paths = ['../../Project', '../../Apps/']
