fail_fast: true
repos:
  - repo: local # Use a local repository
    hooks:
      - id: lint
        name: Lint code
        description: Any color you like
        entry: black .
        args: [
          --config=./Project/settings/pyproject.toml,
          --check
        ]
        files: \*.py
        exclude: /migrations/*
        require_serial: true
        additional_dependencies: ['black==22.3.0']
        always_run: true
        language: python
        language_version: python3

      - id: imports
        name: Sort imports
        description: Isort your imports, so you don't have to
        entry: isort .
        args: [
          --settings-path=./Project/settings/pyproject.toml,
          --check
        ]
        files: \*.py
        exclude: /migrations/*
        require_serial: true
        additional_dependencies: ['isort==5.10.1']
        always_run: true
        language: python
        language_version: python3
        verbose: true

  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
