# Generated by Django 3.2.6 on 2021-09-05 15:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "email",
                    models.EmailField(
                        error_messages={"unique": "This email already exists."},
                        max_length=254,
                        unique=True,
                        verbose_name="Email address",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last name"),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        error_messages={"unique": "This number already exists."},
                        max_length=22,
                        null=True,
                        region=None,
                        unique=True,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("F", "Female"),
                            ("M", "Male"),
                            ("N", "Non-binary"),
                            ("P", "Prefer not to say")
                        ],
                        default="P",
                        max_length=1,
                        null=True,
                        verbose_name="Gender"
                    )
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("EN", "English"),
                            ("ES", "Spanish"),
                            ("FR", "French"),
                            ("OT", "Other")
                        ],
                        default="EN",
                        max_length=2,
                        null=True,
                        verbose_name="Preferred language"
                    )
                ),
                ('birth_date', models.DateField(null=True, verbose_name='Birth date')),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verified"),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="Premium"),
                ),
                ("is_admin", models.BooleanField(default=False, verbose_name="Admin")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "auth_provider",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("facebook", "Facebook"),
                            ("google", "Google"),
                            ("twitter", "Twitter"),
                            ("apple", "Apple"),
                        ],
                        default="email",
                        max_length=10,
                        null=True,
                        verbose_name="Auth provider",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
